infractions/urls.py
from django.urls import path
from . import views

app_name = 'infractions'

urlpatterns = [
	path('', views.index, name='index'),
	path('detail/<int:infractions_speed>', views.detail, name='detail'),
	path('read_json', views.read_json, name='read_json'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('infractions/', include('infractions.urls')),
    path('admin/', admin.site.urls),
]

old/myfirstdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

old/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/actor', views.search_movie, name='search_movie'),
    path('add/movie', views.add_movie, name='add_movie'),
    path('add/actor', views.add_actor, name='add_actor'),
    path('delete/actor', views.delete_actor, name='delete_actor'),
    path('delete/movie', views.delete_movie, name='delete_movie'),
    path('<int:movie_id>/', views.detail, name='detail'),
]

infractions/models.py
from django.db import models

class infraction(models.Model):
    street = models.CharField(max_length=30)
    speed_limit = models.CharField(max_length=30)
    infractions_speed = models.CharField(max_length=30)

infractions/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import infraction

import string
import json

#def __init__(self):
#    infraction.objects.all().delete()
#
#    json_data = open('C:/Users/leyseth/Documents/GitHub/Fines-Django/infractions.json').read()
#
#    input_dict = json.loads(json_data)
#
#    for data in input_dict:
#        infraction.objects.create(street=data['street'], speed_limit=data['speed_limit'], infractions_speed=data['infractions_speed'])

def read_json(request):
    infraction.objects.all().delete()

    json_data = open('C:/Users/leyseth/Documents/GitHub/Fines-Django/infractions.json').read()

    input_dict = json.loads(json_data)

    for data in input_dict:
        infraction.objects.create(street=data['street'], speed_limit=data['speed_limit'], infractions_speed=data['infractions_speed'])

    return render(request, 'read_json.html')

def index(request):

    #infractions_list = infraction.objects.all()

    #return render(request, 'index.html', {'infractions_list': infractions_list})
    return render(request, 'index.html')

def detail(request, infractions_speed):

    #infraction_number = 8
    #number = infraction_number
    #output_dict = [x for x in input_dict if x['infractions_speed'] == infraction_number]

    #out = json_data["infraction_number"]

    i=infraction.objects.all().filter(infractions_speed__gte=infractions_speed).order_by('infractions_speed')


    return render(request, 'detail.html', {'infractions_list': i})

old/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseNotFound
from django.shortcuts import render
import redis
import string
# pattern : "movies":movieid:movieName:GenreName
        #   "actors":movieid:actor_name
r = redis.StrictRedis(host='localhost', port=6379, db=0,  charset="utf-8", decode_responses=True)
class Movie(object):
    def __init__(self, id=None, title=None, genre=None):
        self.id = id
        self.title = title
        self.genre = genre

class Actor(object):
        def __init__(self, name=None, movie_id=None):
                self.name = name
                self.movie_id = movie_id

movie_count = 1

def index(request):
        keys = r.keys('movies:*')
        movieslist = []
        for key in keys:
                m = key.split(":")
                movieslist.append(Movie(m[1],m[2],m[3]))
        movieslist.sort(key=lambda x: x.title)
        return render(request, 'polls/index.html', {'movie_name': movieslist})

def detail(request, movie_id):
        keys = r.keys("actors:" + str(movie_id) + ":*")
        movie_name = r.keys('movies:' + str(movie_id) + "*")[0].split(":")[2]
        actorlist = []
        for key in keys:
                a = key.split(":")
                actorlist.append(Actor(a[2],a[1]))
        actor_name = r.keys("actors:" + str(movie_id) + ":*")
        return render(request, 'polls/detail.html', {'actor_name': actorlist, 'movie_name': movie_name,'movie_id': movie_id})

def search_form(request):
    return render(request, 'polls/index.html', {})

def search_movie(request):
    if request.method == 'POST':
        word = request.POST['search_term']
        result_movies = r.keys("movies:*:" + word + ":*")
        movie = next(iter(result_movies), None)
        movie_id = movie.split(':')[1]
        return detail(request,movie_id)

def add_movie(request):
        if request.method == 'POST':
                movie_name = request.POST['movie_name']
                movie_genre = request.POST['movie_genre']
                global movie_count 
                movie_count += 1
                pattern = 'movies:' + str(movie_count) + ':' + movie_name + ':' + movie_genre
                r.set(pattern,"")
                return index(request)
        else:        
                return render(request, 'polls/add_movie.html', {})
        
def add_actor(request):
        if request.method == 'POST':
                movie_id = request.POST['movie_id']
                actor_name = request.POST['actor_name']
                pattern = "actors:" + movie_id + ":" + actor_name
                r.set(pattern,"")
                return index(request)

def delete_actor(request):
        if request.method == 'POST':
                movie_id = request.POST['movie_id']
                actor_name = request.POST['actor_name']
                pattern = "actors:" + movie_id + ":" + actor_name
                r.delete(pattern)
                return index(request)

def delete_movie(request):
        if request.method == 'POST':
                movie_id = request.POST['movie_id']
                movie_name = request.POST['movie_name']
                movie_genre = request.POST['movie_genre']
                pattern = "movies:" + movie_id + ":" + movie_name + ":" + movie_genre
                keys = r.keys('actors:' + movie_id + '*')
                for actor in keys:
                        r.delete(actor)
                r.delete(pattern)
                return index(request)

infractions/templates/detail.html
<h1>Infractions</h1>
{% block content %}
     <table class="table">
   <thead class="thead-inverse">
     <tr>
       <th>#</th>
       <th>Street</th>
       <th>Speed Limit</th>
       <th>Infractions Speed</th>
     </tr>
   </thead>

   {% for item in infractions_list %}
   <tbody>
     <tr>
       <th scope='row'>1</th>
       <td>{{item.street}}</a></td>
       <td>{{item.speed_limit}}</td>
       <td>{{item.infractions_speed}}</td>
     </tr>
   </tbody>
   {% endfor %}
 </table>
 {% endblock %}


 <h1>Infractions</h1>
 <!--{% for item in infractions_list %}-->
 <tbody>
   <tr>
     <td></td></br>
   </tr>
 </tbody>
 <!--{% endfor %}-->

infractions/templates/index.html
<h1>Infractions</h1>
{% block content %}
     <table class="table">
   <thead class="thead-inverse">
     <tr>
       <th>#</th>
       <th>Street</th>
       <th>Speed Limit</th>
       <th>Infractions Speed</th>
     </tr>
   </thead>

   {% for item in infractions_list %}
   <tbody>
     <tr>
       <th scope='row'>1</th>
       <td>{{item.street}}</a></td>
       <td>{{item.speed_limit}}</td>
       <td>{{item.infractions_speed}}</td>
     </tr>
   </tbody>
   {% endfor %}
 </table>
 {% endblock %}


 <h1>Infractions</h1>
 <!--{% for item in infractions_list %}-->
 <tbody>
   <tr>
     <td></td></br>
   </tr>
 </tbody>
 <!--{% endfor %}-->

infractions/templates/read_json.html
<h1>Infractions in json read </h1>

old/polls/templates/polls/add_movie.html
<h1>Here you can add a movie</h1>
<br/>

<form action='{% url 'polls:add_movie' %}' method='POST'>
{% csrf_token %}
<label for = 'movie_name'>Movie name: </label>
<input id='movie_name' type='text' name='movie_name''>
<br/>
<label for = 'movie_genre'>Movie genre: </label>
<input id='movie_genre' type='text' name='movie_genre''>
<br/>
<input type='submit' value='Add' />
</form>

old/polls/templates/polls/detail.html
<h1>Here are the actors of {{ movie_name }}: </h1>
<br/>
<ul>
    {% for a in actor_name %}
        <li>{{ a.name }} <form action='{% url 'polls:delete_actor' %}' method='POST'>{% csrf_token %}<input type='submit' value='Delete' />
        <input type="hidden" id="movie_id" name="movie_id" value='{{ movie_id }}'>
        <input type="hidden" id="actor_name" name="actor_name" value='{{ a.name }}'></form></li>
    {% endfor %}
</ul>

<br/>
<form action='{% url 'polls:add_actor' %}' method='POST'>
    {% csrf_token %}
    <label for = 'actor_name'>actor name: </label>
    <input id='actor_name' type='text' name='actor_name''>
    <input type="hidden" id="movie_id" name="movie_id" value='{{ movie_id }}'>
    <br/>
    <input type='submit' value='Add' />
</form>

old/polls/templates/polls/index.html
<h1>Movielist</h1>
<br/>
<ul>
    {% for m in movie_name %}
        <li><a href='/polls/{{ m.id }}/'>{{ m.title }}</a>  {{ m.genre }}<form action='{% url 'polls:delete_movie' %}' method='POST'>{% csrf_token %}<input type='submit' value='Delete' />
            <input type="hidden" id="movie_id" name="movie_id" value='{{ m.id }}'>
            <input type="hidden" id="movie_name" name="movie_name" value='{{ m.title }}'>
            <input type="hidden" id="movie_genre" name="movie_genre" value='{{ m.genre }}'></form></li>
    {% endfor %}
</ul>

<h1>Search Quotes</h1>

<form action='{% url 'polls:search_movie' %}' method='POST'>
{% csrf_token %}
<label for = 'search_term'>Your Search : </label>
<input id='search_term' type='text' name='search_term''>
<input type='submit' value='Search' />
</form>